### PR TITLE
refactror: Move osgi from flow

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/flow#9219

### CODE REVIEW

**Comment by caalador** [comment]
Some hamcrest dependency is missing failing the validation

**Comment by denis-anisimov** [comment]
> Some hamcrest dependency is missing failing the validation

Indeed.
Harmcrest has been added to the `master` branch already before I closed it.
I think I have to rebase the branch...
Thanks for the note.

**Comment by denis-anisimov** [comment]
Well, this PR needs Flow SNAPSHOT anyway.

**Review by caalador — APPROVED** [review]

**Review by pleku — APPROVED** [review]
Just one question - what is the rule for when the (public) classes should have the `Osgi..` prefix in the names ? Is it when it is an osgi specific version of something that is already in `flow-server` or ? Just wondering what is the practice we have so we can keep it consistent in the future.

**Comment by denis-anisimov** [comment]
> Just one question - what is the rule for when the (public) classes should have the `Osgi..` prefix in the names ? Is it when it is an osgi specific version of something that is already in `flow-server` or ? Just wondering what is the practice we have so we can keep it consistent in the future.

No any rule.
Just some names. Couldn't figure out anything more meaningfull.
All classes are implementation detail: they should have been private and the name in that case almost doesn't matter.
They are no private just because of framework limitation with DS.
If you five me a list of names to replace I will just copy paste. 
I don't really care which names they have.

**Comment by pleku** [comment]
> If you five me a list of names to replace I will just copy paste.
> I don't really care which names they have.

Well, since then since everything is in an osgi package and inside the osgi artifact and repository, there probably would not be any need to use the prefix. But like you pointed out, not visible to users so there is no concerns regarding API design, it is just about how we want to do it. I don't have any opinion either on this, just wondered if there was some practice. Just let it be

**Comment by denis-anisimov** [comment]
> > If you five me a list of names to replace I will just copy paste.
> > I don't really care which names they have.
> 
> Well, since then since everything is in an osgi package and inside the osgi artifact and repository, there probably would not be any need to use the prefix. But like you pointed out, not visible to users so there is no concerns regarding API design, it is just about how we want to do it. I don't have any opinion either on this, just wondered if there was some practice. Just let it be

OK.

**Pull request merged**
